import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./_providers";
import { Header } from "@/widgets/header";

const font = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${font.className} min-h-[100dvh] bg-gray-light`}>
                <AppProvider>
                    <Header />
                    {children}
                </AppProvider>
            </body>
        </html>
    );
}
